import datetime
import json
import os
import time

import motornet as mn
import numpy as np
import torch as th
import torch.nn.functional as F

from config import ExperimentConfig
from environments import (
    CentreOutReach,
    CentreOutReachCurlField,
    CentreOutReachFixedPosture,
    ContinuousReachCurlField,
    ContinuousReachFixedPosture,
    set_global_seed,
)
from networks import MotorRNN


def resolve_training_envs(config: ExperimentConfig) -> tuple[type, type]:
    """Pick the (null-field, curl-field) reach classes for THIS config's target distribution. Continuous targets force a feedback-driven policy; discrete targets reproduce the Perich-style centre-out fixed target layout. Returns both classes so the interleaved regime can pair them.
    """
    
    if config.target_distribution == 'continuous':
        return ContinuousReachFixedPosture, ContinuousReachCurlField
    elif config.target_distribution == 'discrete':
        return CentreOutReachFixedPosture, CentreOutReachCurlField
    raise ValueError(f"Unknown target_distribution: {config.target_distribution!r}")

def build_task_input(obs, goal, state_estimate, config, dims):
    """Assembles [goal, delayed vision, optionally delayed proprioception, optionally the Predictive Network's estimate] into one vector for the Task Network's input layout.
    Its full input dimension is 16 because it receives:\n
    *	2-D Goal: The Cartesian X, Y coordinates of the target (Visual Cortex).
    *	2-D Vision: The Cartesian X, Y coordinates of the fingertip (Visual Cortex).
    *	12-D State Estimate: The delay-compensated prediction of the 6 muscle lengths and velocities, generated by the Predictive Network.
    """
    g, v, p = dims["goal"], dims["vision"], dims["prop"]
    vision_obs = obs[:, g:g + v]                  # delayed fingertip Cartesian position
    parts = [goal, vision_obs]
    if config.task_receives_feedback:             # monolithic: raw delayed proprioception
        parts.append(obs[:, g + v:g + v + p])
    if state_estimate is not None:                # dual: delay-compensated estimate x̂
        parts.append(state_estimate.detach())    # stop-gradient: J_task must not train pred_net
    return th.cat(parts, dim=-1)

def build_pred_input(obs, task_net_output, config, dims):
    """Assembles the Predictive Network's input: efference copy of the motor command and optionally the delayed proprioceptive feedback (the internal state to roll forward from)."""
    g, v, p = dims["goal"], dims["vision"], dims["prop"]
    parts = [task_net_output.detach()]               # stop-gradient: J_pred must not train task_net
    if config.predictive_receives_feedback:
        parts.append(obs[:, g + v:g + v + p].detach())
    return th.cat(parts, dim=-1)

def task_input_layout(config: ExperimentConfig, dims: dict) -> list:
    """Ordered ``(block_name, column_slice)`` of the Task Net input vector — the single source of truth for the layout assembled by :func:`build_task_input`:
    ``[goal | vision | (proprioception) | (state_estimate)]``. Proprioception is present iff the task net receives raw feedback (always true for mono after :func:`construct_architecture`); the predictive state-estimate iff the architecture is dual. Used by the input-layer training trace here and by the weight-inspection probe in evaluation."""
    
    g, v, p = dims["goal"], dims["vision"], dims["prop"]
    sizes = [("goal", g), ("vision", v)]
    if config.task_receives_feedback:
        sizes.append(("proprioception", p))
    if config.architecture == "dual":
        sizes.append(("state_estimate", p))
    layout, start = [], 0
    for name, size in sizes:
        layout.append((name, slice(start, start + size)))
        start += size
    return layout

def construct_architecture(config: ExperimentConfig, env: mn.environment.Environment, device: th.device) -> tuple:
    # Dual network has the same capacity as the monolithic network, but split between the Task and Predictive Networks according to the predictive_split_ratio.
    if config.architecture == 'dual':
        pred_units = int(config.hidden_units * config.predictive_split_ratio)
        task_units = config.hidden_units - pred_units
    else:
        task_units = config.hidden_units
        pred_units = 0
        config.task_receives_feedback = True

    goal_dim = env.obs_dims["goal"]     # Cartesian x and y coordinates of the static target position
    vision_dim = env.obs_dims["vision"] # Cartesian x and y coordinates of the endpoint (coresponding to effector.states["fingertip"] in MotorNet)
    prop_dim = env.obs_dims["prop"]     # Proprioceptive feedback consists of muscle lengths and muscle lengthening velocities for each muscle
    # The Predictive Network outputs a de-delayed estimate of the PROPRIOCEPTIVE feedback (muscle length + velocity) — the same 12-D signal the delayed feedback carries, but for the current timestep. This is the OFC state-estimator role: estimate the sensory consequence, delay-compensated; it excludes the large / spiky force terms that destabilised the earlier loss.
    estimate_dim = prop_dim  # = env.n_muscles * 2, the observation-space proprioception

    # Task Network Input Dimensions: acts as the inverse model, transforming extrinsic spatial goals (visual coordinates such as where the hand and the target are located in the external world) into intrinsic motor commands.
    task_input_dim = goal_dim + vision_dim # Visual input must be routed exclusively to the Task Network: mixing extrinsic visual coordinates into the intrinsic cerebellar loop would violate the biological division of labour (visual stream vs spinocerebellar tract)
    if config.task_receives_feedback:
        task_input_dim += prop_dim
    if pred_units > 0:
        task_input_dim += estimate_dim

    # Predictive Network Input Dimensions: acts as the forward model, predicting future intrinsic states (muscle physics) from current intrinsic states (proprioception: internal lengths, velocities, and tensions of the muscles). Its input dimension is 18 because it receives:
    # - 6-D Efference Copy: The motor commands just issued by the Task Network for the 6 muscles.
    # - 12-D Delayed Proprioception: The raw sensory feedback arriving from the simulated muscle spindles.
    pred_input_dim = env.n_muscles
    if config.predictive_receives_feedback:
        pred_input_dim += prop_dim

    # Instantiate Task Network
    task_network = MotorRNN(
        input_dim=task_input_dim, 
        hidden_dim=task_units, 
        output_dim=env.n_muscles, 
        device=device, 
        is_task_network=True,
        effector_type=config.effector_type
    )
    
    # Instantiate Predictive Network
    predictive_network = None
    if pred_units > 0:
        predictive_network = MotorRNN(
            input_dim=pred_input_dim,
            hidden_dim=pred_units,
            output_dim=estimate_dim,
            device=device,
            is_task_network=False,
            effector_type=config.effector_type
        )
        
    return task_network, predictive_network

def compute_spatial_loss(loss_type: str, fingertip_traj: th.Tensor, goal_pos: th.Tensor, temporal_mode: str = 'continuous', target_radius: float = 0.0, delta: float = 0.05) -> th.Tensor:
    """
    Spatial position-to-target loss, with two selectable temporal modes, loss type, and an optional target-radius dead-zone.\n
 
    temporal_mode:
    * 'terminal'   — penalise only the FINAL timestep (the original baseline objective)
    * 'continuous' — integrate the position error over the WHOLE trajectory (the OFC state-error objective) to incentivise movement initiation immediateley (as opposed to sudden movement initiation towards the end of the episode)      
 
    loss_type (the per-step penalty on the dead-zoned distance):
    * 'huber' - quadratic near the target (less than delta), linear for large transient errors. Prevents gradient explosions during violent elastic recoils (whiplash) whilst preserving a convex mathematical landscape for fine sub-centimetre precision near the target.
    * 'mae'   — L1. Constant linear penalty regardless of error magnitude.  However, it is highly vulnerable to endless oscillation around the target coordinate, as the gradient magnitude does not smoothly decay to zero as the fingertip approaches the goal, unless a dead-zone is used.
    * 'mse'   — L2 (squared distance). Heavier weighting of large early errors. Best suited for rigid effectors or unperturbed kinematics where trajectory errors remain small and normally distributed. It is highly vulnerable to causing catastrophic forgetting if applied to compliant tendons, as physical outliers generate explosive gradients.\n
 
    target_radius: dead-zone (m). Following the MotorNet implementation (Codol et al. 2024; Codol & Perich), a non-zero radius gives an explicit tolerance which flattens the gradient lanscape inside the radius to stabilise the arm and settle on the target without the gradient jumping around. Preferably used with 'mae' loss and set to 0 if using a 'huber' loss.
 
    fingertip_traj: [B, T, 2]; goal_pos: [B, 2].
    """
    goal_pos = goal_pos.unsqueeze(1)                            # [B, 1, 2]
    if temporal_mode == 'terminal':
        diff = fingertip_traj[:, -1:, :] - goal_pos             # [B, 1, 2] final step only
    elif temporal_mode == 'continuous':
        diff = fingertip_traj - goal_pos                        # [B, T, 2] whole trajectory
    else:
        raise ValueError(f"Unrecognised temporal_mode: {temporal_mode}")
 
    dist = th.linalg.norm(diff, dim=-1)                         # [B, *]
    err = th.clamp(dist - target_radius, min=0.0)              # dead-zone (no-op when radius = 0)
 
    if loss_type == 'huber':
        return F.huber_loss(err, th.zeros_like(err), delta=delta)
    elif loss_type == 'mse':
        return th.mean(err ** 2)
    elif loss_type == 'mae':
        return th.mean(err)
    else:
        raise ValueError(f"compute_spatial_loss: Unrecognised loss_type: {loss_type}")

def compute_velocity_loss(cartesian_vel_traj: th.Tensor) -> th.Tensor:
    """Mean squared fingertip speed over the WHOLE trajectory, uniformly weighted.

    Motivation: a ballistic reach that leaves residual endpoint velocity at the target has that velocity amplified by the velocity-dependent curl field,
    producing post-reach drift. The spatial position loss under-penalises this because a small residual speed is only a small position error at any instant. An explicit speed penalty supplies a direct hold signal.

    The penalty is applied uniformly at every timestep rather than being gated by an arbitrarily-defined hold window. It still concentrates its effect in the hold, but by competition rather than by construction: during the reach the position term dominates and requires velocity (moving) to be reduced. Only in the hold, once the position term has gone quiet (the fingertip is on target), does the speed penalty become the dominant remaining cost and drive residual velocity to zero. Uniform weighting therefore self-allocates to the hold without an arbitrary "when does the hold begin" boundary, and — unlike a
    hold-gated penalty — it also constrains the reach profile rather than leaving it free.

    cartesian_vel_traj: [B, T, 2] fingertip (v_x, v_y) at each step.
    """
    return th.mean((cartesian_vel_traj ** 2).sum(dim=-1))  # mean over batch & time of speed^2 (m^2/s^2)

_FEEDBACK_BLOCKS = ("vision", "proprioception", "state_estimate")


def compute_feedback_gain_penalty(task_net, input_layout: list) -> th.Tensor:
    """Sum of squared Task-Net GRU input weights on the FEEDBACK-derived input blocks (vision +
    proprioception + predictive estimate), excluding the goal. Penalising this shrinks the feedforward
    feedback pathway, lowering the controller's feedback gain — the mechanism for the 'matched-gain
    mono' control (train a mono down to the dual's gain, then test whether it is still delay-fragile).
    A weight-space proxy for the behavioural gain (prop-freeze / intact error), so calibrate the
    penalty weight against that ablation ratio rather than in absolute units."""
    W = task_net.gru.weight_ih_l0                       # [3*hidden, input_dim]
    penalty = W.new_zeros(())
    for name, sl in input_layout:
        if name in _FEEDBACK_BLOCKS:
            penalty = penalty + (W[:, sl] ** 2).sum()
    return penalty


def compute_predictive_loss(loss_type: str, preds: th.Tensor, actuals: th.Tensor, delta: float = 0.05) -> th.Tensor:
    """
    Computes the state estimation error for the Predictive Network. Matches the gradient regularisation strategy of the Task Network to ensure internal physics representations remain stable during elastic transients.
    """
    if loss_type == 'huber':
        return F.huber_loss(preds, actuals, delta=delta)
    elif loss_type == 'mse':
        # Averages the error equally across all physical variables, time steps, and batches
        return th.mean((preds - actuals) ** 2)
    elif loss_type == 'mae':
        return th.mean(th.abs(preds - actuals))
    else:
        raise ValueError(f"compute_predictive_loss: Unrecognised loss_type: {loss_type}")

def is_improvement(current: float, best: float, mode: str, min_delta: float, min_rel_delta: float) -> bool:
    """Whether the rolling-mean loss ``current`` beats ``best`` by enough to RESET patience.

    mode:
    * 'absolute' — ``current < best - min_delta``           (fixed loss-unit margin)
    * 'relative' — ``current < best * (1 - min_rel_delta)`` (fractional margin; scale-free, so the same setting behaves consistently whether the loss sits at 1e-2 or 1e-5)

    'none' is handled by the caller (the whole stopping check is skipped), so it never reaches here.
    """
    if mode == 'absolute':
        return current < best - min_delta
    if mode == 'relative':
        return current < best * (1.0 - min_rel_delta)
    raise ValueError(f"Unknown early_stopping mode: {mode!r}; expected 'none', 'absolute' or 'relative'.")


class EarlyStopper:
    """Patience-based early-stopping tracker over a rolling mean of the loss.

    Owns all the convergence bookkeeping that used to live as loose locals in the training loop: per-channel rolling-mean buffer, best-so-far, and patience counter. Tracks one channel (task only) or two (task + predictive); for the dual architecture BOTH channels must plateau before training stops.

    At each evaluation call :meth:`update` appends the latest loss, recomputes the rolling mean, resets patience on a qualifying improvement (per :func:`is_improvement` and ``config.early_stopping``) or increments it otherwise, and returns ``True`` once every tracked channel has both a full window and patience >= ``patience_limit``. When ``config.early_stopping == 'none'`` the tracker is disabled and :meth:`update` always returns ``False``.
    """

    def __init__(self, config: ExperimentConfig, track_predictive: bool):
        self.config = config
        self.enabled = config.early_stopping != 'none'
        self.track_predictive = track_predictive
        self.task = {"buffer": [], "best": float('inf'), "patience": 0}
        self.pred = {"buffer": [], "best": float('inf'), "patience": 0} if track_predictive else None

    def _update_channel(self, ch: dict, value: float) -> None:
        """Append ``value`` to the channel's rolling buffer and update its best/patience."""
        ch["buffer"].append(value)
        if len(ch["buffer"]) > self.config.window_size:
            ch["buffer"].pop(0)
        current = sum(ch["buffer"]) / len(ch["buffer"])
        if is_improvement(current, ch["best"], self.config.early_stopping, self.config.min_delta, self.config.min_rel_delta):
            ch["best"] = current
            ch["patience"] = 0   # Improvement found, reset counter
        else:
            ch["patience"] += 1  # No meaningful improvement, increment patience

    def _plateaued(self, ch: dict) -> bool:
        """A channel has converged once it has a full window and exhausted its patience."""
        return len(ch["buffer"]) == self.config.window_size and ch["patience"] >= self.config.patience_limit

    def update(self, epoch: int, task_loss: float, pred_loss: float | None = None) -> bool:
        """Record this evaluation's loss(es); return ``True`` if training should stop."""
        if not self.enabled:
            return False
        self._update_channel(self.task, task_loss)
        if self.track_predictive:
            self._update_channel(self.pred, pred_loss)
            if self._plateaued(self.task) and self._plateaued(self.pred):
                print(f"\nConvergence reached at Epoch {epoch}. Both networks plateaued at "
                      f"{self.task['best']:.4e} task network & {self.pred['best']:.4e} predictive network.")
                return True
        elif self._plateaued(self.task):
            print(f"\nConvergence reached at Epoch {epoch}. Task network plateaued at {self.task['best']:.4e}.")
            return True
        return False


def train_model(config: ExperimentConfig, task_net: MotorRNN, pred_net: MotorRNN, env: mn.environment.Environment, device: th.device, curl_env: mn.environment.Environment | None = None, resume_from: str | None = None):
    """
    Executes the dual-loss Backpropagation Through Time loop.

    If config.training_regime == 'interleaved', `curl_env` must be supplied: each epoch is then either a null-field epoch (using `env`) or a curl-field epoch (using `curl_env`), chosen by a dedicated, separately-seeded RNG so the null / curl sequence is reproducible and identical across architectures (otherwise the training curriculum becomes an uncontrolled confound on the dual-vs-mono comparison).

    `resume_from`: path to a run directory whose `training_state.pt` (written each validation) is loaded to continue an interrupted run — restores weights, optimizer state, RNG, epoch, best-so-far, loss histories and the early-stopping state, then trains on in the SAME directory from where it left off.
    """

    dims = env.obs_dims

    if config.early_stopping not in ('none', 'absolute', 'relative'):
        raise ValueError(f"Unknown early_stopping: {config.early_stopping!r}; expected 'none', 'absolute' or 'relative'.")
    if config.early_stopping == 'none':
        print(f"Early stopping DISABLED: training to the full {config.max_epochs} epochs.")
    else:
        print(f"Early stopping = '{config.early_stopping}' | patience {config.patience_limit} checks @ every {config.evaluation_interval} epochs "
              f"| margin {'min_delta=' + format(config.min_delta, '.1e') if config.early_stopping == 'absolute' else 'min_rel_delta=' + format(config.min_rel_delta, '.1%')}.")

    interleaved = (config.training_regime == 'interleaved')
    if interleaved:
        if curl_env is None:
            raise ValueError("training_regime='interleaved' requires a curl_env.")
        # Separate generator so the perturbation schedule does NOT consume from (or perturb) the global RNG stream that drives weight init, batching, targets.
        perturb_rng = th.Generator(device='cpu')
        perturb_rng.manual_seed(config.perturb_seed)
        perturb_schedule = []   # logged per-epoch for inspection post-training

    task_optimizer = th.optim.Adam(task_net.parameters(), lr=config.lr)
    if pred_net is not None:
        pred_optimizer = th.optim.Adam(pred_net.parameters(), lr=config.lr)

    task_loss_history = []
    pred_loss_history = []
    effort_loss_history = []
    velocity_loss_history = []

    stopper = EarlyStopper(config, track_predictive=pred_net is not None)

    # Input-layer training trace: per-block weight norm and (post-clip) gradient norm of the Task Net's GRU input matrix, recorded every evaluation_interval. Answers "is the input layer — especially the feedback slice — actually training?": a feedback-block grad that sits at ~0 throughout means gradient descent never pushes the net to use the channel.
    input_layout = task_input_layout(config, dims)
    wnorm_trace = {name: [] for name, _ in input_layout}
    gnorm_trace = {name: [] for name, _ in input_layout}
    trace_epochs = []

    best_val = float('inf')
    best_epoch = -1
    val_history = []        # (epoch, val_spatial_loss, val_terminal_error_cm) rows
    start_epoch = 0

    # RUN DIRECTORY. Only the BEST-validation model is kept (task_net.pth). Each validation ALSO writes the loss logs and a full resume checkpoint (training_state.pt), so an interrupted run stays fully plottable and can be resumed. `resume_from` reloads that checkpoint and continues in the same dir.
    if resume_from is not None:
        run_directory = os.path.abspath(resume_from)
        state = th.load(os.path.join(run_directory, "training_state.pt"), map_location=device, weights_only=False)
        task_net.load_state_dict(state["task_net"]); task_optimizer.load_state_dict(state["task_optimizer"])
        if pred_net is not None:
            pred_net.load_state_dict(state["pred_net"]); pred_optimizer.load_state_dict(state["pred_optimizer"])
            pred_loss_history = state["pred_loss_history"]
        th.set_rng_state(state["rng_state"])
        if interleaved and state.get("perturb_rng_state") is not None:
            perturb_rng.set_state(state["perturb_rng_state"]); perturb_schedule = state["perturb_schedule"]
        start_epoch = state["epoch"] + 1
        best_val, best_epoch = state["best_val"], state["best_epoch"]
        task_loss_history, effort_loss_history = state["task_loss_history"], state["effort_loss_history"]
        velocity_loss_history, val_history = state["velocity_loss_history"], state["val_history"]
        wnorm_trace, gnorm_trace, trace_epochs = state["wnorm_trace"], state["gnorm_trace"], state["trace_epochs"]
        stopper.task, stopper.pred = state["stopper_task"], state["stopper_pred"]
        print(f"Resuming from {run_directory} at epoch {start_epoch} (best so far: epoch {best_epoch}, val {best_val:.4e}).")
    else:
        arch_dir = f"{config.architecture}_{config.hidden_units}u_split{config.predictive_split_ratio}"
        task_dir = f"{config.loss_function}_{config.spatial_loss_temporal_mode}_{config.training_regime}_{env.__class__.__name__}"
        # Seed-tagged so multi-seed replicates of the same config land in sibling folders instead of overwriting.
        run_timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M") + f"_seed{config.seed}"
        src_directory = os.path.dirname(os.path.abspath(__file__))
        run_directory = os.path.abspath(os.path.join(src_directory, "..", "results", config.effector_type, arch_dir, task_dir, run_timestamp))
        os.makedirs(run_directory, exist_ok=True)
        config.save_to_json(os.path.join(run_directory, "config.json"))
        print(f"Run directory (best model + logs + resume checkpoint saved here):\n{run_directory}")

    def save_logs():
        """Loss/trace histories (no model weights) — for the learning-curve + validation-curve plots."""
        np.save(os.path.join(run_directory, "task_loss.npy"), np.array(task_loss_history))
        np.save(os.path.join(run_directory, "effort_loss.npy"), np.array(effort_loss_history))
        np.save(os.path.join(run_directory, "velocity_loss.npy"), np.array(velocity_loss_history))
        np.save(os.path.join(run_directory, "val_metrics.npy"), np.array(val_history, dtype=float))  # [K,3]: epoch, spatial_loss, terminal_err_cm
        trace = {"epochs": np.array(trace_epochs)}
        for name in wnorm_trace:
            trace[f"wnorm_{name}"] = np.array(wnorm_trace[name])
            trace[f"gnorm_{name}"] = np.array(gnorm_trace[name])
        np.savez(os.path.join(run_directory, "input_layer_trace.npz"), **trace)
        if pred_net is not None:
            np.save(os.path.join(run_directory, "pred_loss.npy"), np.array(pred_loss_history))
        if config.training_regime == 'interleaved':
            np.save(os.path.join(run_directory, "perturb_schedule.npy"), np.array(perturb_schedule, dtype=bool))

    def save_best(at_epoch: int, val: float, term_cm: float):
        """The BEST-validation model — task_net.pth is what evaluation loads."""
        th.save(task_net.state_dict(), os.path.join(run_directory, "task_net.pth"))
        if pred_net is not None:
            th.save(pred_net.state_dict(), os.path.join(run_directory, "pred_net.pth"))
        with open(os.path.join(run_directory, "best_checkpoint.json"), "w") as f:
            json.dump({"best_epoch": at_epoch, "best_val_loss": val, "best_val_terminal_error_cm": term_cm,
                       "metric": f"{config.spatial_loss_temporal_mode}_spatial_loss_unperturbed",
                       "validation_seed": config.validation_seed,
                       "validation_batch_size": config.validation_batch_size}, f, indent=2)

    def save_training_state(at_epoch: int):
        """Full state to resume the LATEST training position (weights, optimizer, RNG, epoch, best, histories)."""
        state = {"epoch": at_epoch, "task_net": task_net.state_dict(), "task_optimizer": task_optimizer.state_dict(),
                 "rng_state": th.get_rng_state(), "best_val": best_val, "best_epoch": best_epoch,
                 "task_loss_history": task_loss_history, "effort_loss_history": effort_loss_history,
                 "velocity_loss_history": velocity_loss_history, "val_history": val_history,
                 "wnorm_trace": wnorm_trace, "gnorm_trace": gnorm_trace, "trace_epochs": trace_epochs,
                 "stopper_task": stopper.task, "stopper_pred": stopper.pred}
        if pred_net is not None:
            state["pred_net"] = pred_net.state_dict(); state["pred_optimizer"] = pred_optimizer.state_dict()
            state["pred_loss_history"] = pred_loss_history
        if interleaved:
            state["perturb_rng_state"] = perturb_rng.get_state(); state["perturb_schedule"] = perturb_schedule
        th.save(state, os.path.join(run_directory, "training_state.pt"))

    def validate():
        """Score the model on the FIXED held-out unperturbed batch. Returns (spatial_loss, terminal_error_cm).
        The RNG state is saved/restored so the same targets are scored each call and training's stream is untouched."""
        rng_state = th.get_rng_state()
        th.manual_seed(config.validation_seed)
        vb = config.validation_batch_size
        task_net.eval()
        if pred_net is not None:
            pred_net.eval()
        with th.no_grad():
            obs, info = env.reset(options={"batch_size": vb})   # env is the null-field (unperturbed) task
            h_task = task_net.init_hidden(vb)
            se = None
            if pred_net is not None:
                h_pred = pred_net.init_hidden(vb)
                se = th.zeros(vb, dims["prop"], device=device)
            ti = build_task_input(obs, info["goal"], se, config, dims)
            ftips, terminated = [], False
            while not terminated:
                cmd, h_task = task_net(ti, h_task)
                obs, _, terminated, _, info = env.step(action=cmd)
                ftips.append(info["states"]["fingertip"])
                se = None
                if pred_net is not None:
                    se, h_pred = pred_net(build_pred_input(obs, cmd, config, dims), h_pred)
                ti = build_task_input(obs, info["goal"], se, config, dims)
            traj = th.stack(ftips, dim=1)   # [B, T, 2]
            vloss = compute_spatial_loss(config.loss_function, traj, info["goal"],
                                         config.spatial_loss_temporal_mode, config.target_radius, config.huber_delta)
            term_cm = float((th.linalg.norm(traj[:, -1, :] - info["goal"], dim=-1).mean() * 100).item())
        task_net.train()
        if pred_net is not None:
            pred_net.train()
        th.set_rng_state(rng_state)
        return float(vloss.item()), term_cm

    for epoch in range(start_epoch, config.max_epochs):
        # INITIALISATION (t = 0): Reset environment and recurrent states
        # In the interleaved regime, choose null vs curl env for THIS epoch up front.
        if interleaved:
            is_curl_epoch = bool(th.rand(1, generator=perturb_rng).item() < config.perturb_fraction)
            perturb_schedule.append(is_curl_epoch)
            active_env = curl_env if is_curl_epoch else env
        else:
            active_env = env
            
        terminated = False
        reset_obs, info = active_env.reset(options={"batch_size": config.batch_size})
        h_task = task_net.init_hidden(config.batch_size)
        state_estimate = None
        if pred_net is not None:
            h_pred = pred_net.init_hidden(config.batch_size)
            state_estimate = th.zeros(config.batch_size, dims["prop"], device=device)  # no estimate yet at t=0
        task_net_input = build_task_input(reset_obs, info["goal"], state_estimate, config, dims)

        # Trajectory tracking lists
        u_t_list = []           # Store the Task Network's motor command output (the actual control signal sent to the muscles at each time step)
        fingertip_list = []     # Store the TRUE (undelayed) fingertip position at each step; stacked into the continuous spatial loss
        cartesian_vel_list = [] # Store the TRUE fingertip Cartesian velocity (v_x, v_y) at each step, for the velocity penalty
        pred_states_list = []   # Store the Predictive Network's state estimates at each time step for calculating the predictive network's loss
        obs_prop_list = []      # Store the actual muscle states at each time step for calculating the predictive network's loss

        # TEMPORAL PHYSICS LOOP UNTIL MAX EPISODE DURATION EXCEEDED (stopping when the target is reached will lead to "punching" through the target as quickly as possible rather than learning to smoothly decelerate into the target)
        while not terminated:
            # Forward pass through Task Network, processes the current task_net_input to generate a command
            task_net_output, h_task = task_net(task_net_input, h_task)
            u_t_list.append(task_net_output)

            # Step the environment with the Task Network's motor command output and gather new (delayed) feedback / observations
            delayed_obs, reward, terminated, truncated, info = active_env.step(action=task_net_output)

            fingertip_list.append(info["states"]["fingertip"])   # true (undelayed) position, for the trajectory loss
            cartesian_vel_list.append(info["states"]["cartesian"][:, 2:4])  # true (v_x, v_y), for the velocity penalty

            state_estimate = None
            if pred_net is not None:
                g, v, p = dims["goal"], dims["vision"], dims["prop"]
                prop_obs = delayed_obs[:, g + v:g + v + p]       # delayed proprioception = true state at t-delta

                pred_net_output, h_pred = pred_net(build_pred_input(delayed_obs, task_net_output, config, dims), h_pred)

                pred_states_list.append(pred_net_output)          # x_t — kept attached, so J_pred trains pred_net
                obs_prop_list.append(prop_obs.detach())           # target source, same observation space
                state_estimate = pred_net_output.detach()         # detached to sever the task graph

            task_net_input = build_task_input(delayed_obs, info["goal"], state_estimate, config, dims)

        # BPTT AND OPTIMISATION BLOCK
        fingertips = th.stack(fingertip_list, dim=1)              # [B, T, 2] full trajectory
        spatial_loss = compute_spatial_loss(
            loss_type=config.loss_function,
            fingertip_traj=fingertips,
            goal_pos=info["goal"],
            temporal_mode=config.spatial_loss_temporal_mode,
            target_radius=config.target_radius,
            delta=config.huber_delta,
        )
        # Terminal metrics for LOGGING ONLY:
        #   - euclidean_dist (distance to target at the final step)
        #   - terminal_speed (should fall toward ~0 once it learns to hold)
        euclidean_dist = th.linalg.norm(info["states"]["fingertip"] - info["goal"], dim=-1).mean().detach()
        terminal_speed = th.linalg.norm(info["states"]["cartesian"][:, 2:4], dim=-1).mean().detach() 
        
        # Muscle Effort Penalty (L2 Regularisation)
        # Stack the motor commands across the entire trajectory: shape [batch_size, time_steps, n_muscles]
        commands_tensor = th.stack(u_t_list, dim=1)
        effort_loss = th.mean(commands_tensor ** 2)

        # Velocity Penalty: mean squared fingertip speed over the WHOLE trajectory, uniformly weighted.
        cartesian_vels = th.stack(cartesian_vel_list, dim=1)      # [B, T, 2]
        velocity_loss = compute_velocity_loss(cartesian_vels)

        # Total Task Loss
        J_task = spatial_loss + (config.effort_penalty_weight * effort_loss) + (config.velocity_penalty_weight * velocity_loss)

        # Feedback-gain penalty ('matched-gain mono' control): shrink the Task Net's feedback input weights.
        gain_penalty_value = 0.0
        if config.feedback_gain_penalty_weight > 0.0:
            gain_penalty = compute_feedback_gain_penalty(task_net, input_layout)
            J_task = J_task + config.feedback_gain_penalty_weight * gain_penalty
            gain_penalty_value = gain_penalty.item()

        # Calculate Predictive Loss (Instantaneous State Estimation Error): Mean squared error between the predicted and ground-truth physical states, averaging equally across physical variables, the full temporal trajectory, and the independent trials within the batch.
        J_pred = None
        if pred_net is not None:
            preds = th.stack(pred_states_list, dim=1)         # [B, T, 12]  x_t at each step
            obs_prop = th.stack(obs_prop_list, dim=1)         # [B, T, 12]  delayed prop = true state at t-delta
            dp = env.proprioception_delay                     # actual delay in TIMESTEPS the env runs (single source of truth), not the ms config value
            T = preds.shape[1]

            # x_t predicts the CURRENT true proprioception (true_t). The delayed channel only reports true_t at step t+dp, so the target for x_t is obs_prop[t+dp]. Align by shifting, and drop the final dp steps which have no future observation to score against.
            J_pred = compute_predictive_loss(
                config.loss_function,
                preds[:, :T - dp, :],
                obs_prop[:, dp:, :],
                delta=config.huber_delta,
            )

        # Confirms the stop-gradient holds: neither loss should reach the other network.
        # retain_graph=True on both so the graphs survive for the real optimizer steps below.
        if epoch == 0 and pred_net is not None:
            task_net.zero_grad()
            pred_net.zero_grad()
            J_task.backward(retain_graph=True)
            assert all(p.grad is None or th.all(p.grad == 0) for p in pred_net.parameters()), "LEAK: J_task reached pred_net"
            task_net.zero_grad()
            pred_net.zero_grad()
            J_pred.backward(retain_graph=True)
            assert all(p.grad is None or th.all(p.grad == 0) for p in task_net.parameters()), "LEAK: J_pred reached task_net"
            print("Stop-gradient verified: graphs are disjoint.")
            task_net.zero_grad() 
            pred_net.zero_grad()  # clean up before real backward passes

        # Update Task Network
        task_optimizer.zero_grad()
        J_task.backward()
        th.nn.utils.clip_grad_norm_(task_net.parameters(), max_norm=1.0)
        task_optimizer.step()

        # Update Predictive Network
        if pred_net is not None:
            pred_optimizer.zero_grad()
            J_pred.backward()
            th.nn.utils.clip_grad_norm_(pred_net.parameters(), max_norm=1.0)
            pred_optimizer.step()
        
        task_loss_history.append(J_task.item())
        effort_loss_history.append(effort_loss.item())
        velocity_loss_history.append(velocity_loss.item())
        if pred_net is not None:
            pred_loss_history.append(J_pred.item())

        # INPUT-LAYER TRAINING TRACE: read the Task Net's GRU input weights and their grads (post-clip, pre next zero_grad — i.e. the update that was actually applied this epoch), split by input block. Recorded every evaluation_interval to keep it cheap.
        if epoch % config.evaluation_interval == 0:
            W = task_net.gru.weight_ih_l0                 # [3H, D]
            G = W.grad
            trace_epochs.append(epoch)
            for name, sl in input_layout:
                wnorm_trace[name].append(float(W[:, sl].detach().norm()))
                gnorm_trace[name].append(float(G[:, sl].norm()) if G is not None else float('nan'))

        # PATIENCE-BASED STOPPING PROTOCOL (the EarlyStopper is a no-op when config.early_stopping == 'none')
        if stopper.enabled and epoch % config.evaluation_interval == 0:
            if stopper.update(epoch, J_task.item(), J_pred.item() if pred_net is not None else None):
                break

        if epoch % 250 == 0:
            string = f"Epoch {epoch} | Task Loss ({config.loss_function}): {J_task.item():.4e} | Spatial Loss: {spatial_loss.item():.4e} | Dist: {euclidean_dist.item()*100:.2f}cm | Speed: {terminal_speed.item()*100:.2f}cm/s | Effort Loss: {config.effort_penalty_weight * effort_loss.item():.4e} | Effort Loss %: {config.effort_penalty_weight * effort_loss.item() / J_task.item() * 100:.2f}%"
            if config.velocity_penalty_weight > 0.0:
                string += f" | VelPen: {velocity_loss.item():.4e} | VelPen %: {config.velocity_penalty_weight * velocity_loss.item() / J_task.item() * 100:.2f}%"
            if config.feedback_gain_penalty_weight > 0.0:
                string += f" | GainPen: {config.feedback_gain_penalty_weight * gain_penalty_value:.4e}"
            if pred_net is not None:
                string += f" | Pred Loss: {J_pred.item():.4e}"
            if interleaved:
                string += f" | is_curl_epoch: {is_curl_epoch}"
            print(string)

        # BEST-MODEL VALIDATION on the held-out unperturbed batch (0 disables). Also refreshes the loss
        # logs + resume checkpoint so an interrupted run stays fully plottable and resumable.
        if config.validation_interval and epoch % config.validation_interval == 0:
            vloss, vterm = validate()
            val_history.append((epoch, vloss, vterm))
            if vloss < best_val:
                best_val, best_epoch = vloss, epoch
                save_best(epoch, vloss, vterm)
            save_logs()
            save_training_state(epoch)

    # Validation disabled => no best was ever saved; fall back to keeping the final-epoch model.
    if best_epoch < 0:
        save_best(epoch, float('nan'), float('nan'))
    save_logs()
    save_training_state(epoch)
    if best_epoch >= 0:
        print(f"Best model: epoch {best_epoch} (val loss {best_val:.4e}) -> task_net.pth")
    print(f"Training complete. Artefacts saved with prefix: \n{run_directory}")
    return run_directory
        

if __name__ == "__main__":
    start_timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    start_perf_time = time.perf_counter()

    print("\n--- Execution Initiated ---")
    print(f"Start Time: {start_timestamp}")
    
    device = th.device("cuda" if th.cuda.is_available() else "cpu")
    
    dev_test_config = ExperimentConfig(
        architecture='mono',
        predictive_split_ratio=0.5,
        loss_function='huber', 
        huber_delta=0.05,
        target_radius=0.0,               
        spatial_loss_temporal_mode='continuous',
        effort_penalty_weight=5e-2,
        velocity_penalty_weight=5e-3,    # starting point
        task_receives_feedback=False,
        predictive_receives_feedback=True,
        context_provided=False,
        target_distribution='continuous',
        training_regime='interleaved',
        curl_randomise_sign=True,                   # per-trial CW/CCW => unpredictable field => must use feedback
        curl_magnitude_jitter=0.25,                 # +/-25% magnitude spread around curl_viscosity
        hidden_units=64,
        effector_type='rigid_arm26',
        max_ep_duration=0.5,
        max_epochs=1000,
        batch_size=16
    )
    full_run_test_config = ExperimentConfig(
        architecture='dual',                        # 'dual' or 'mono'
        predictive_split_ratio=0.5,
        loss_function='huber', 
        huber_delta=0.05,
        target_radius=0.0,               
        spatial_loss_temporal_mode='continuous',    # 'terminal' or 'continuous'
        effort_penalty_weight=1e-4,                 # 1e-4
        velocity_penalty_weight=5e-3,               # 5e-3, whole-trajectory speed penalty
        task_receives_feedback=False,
        predictive_receives_feedback=True,
        context_provided=False,
        target_distribution='continuous',           # 'discrete' (Perich-style 8-target eval) or 'continuous' (forces feedback control)
        training_regime='interleaved',              # 'unperturbed' or 'interleaved'
        curl_randomise_sign=False,                  # per-trial CW/CCW => unpredictable field => must use feedback
        curl_magnitude_jitter=0,                    # +/-25% magnitude spread around curl_viscosity
        hidden_units=128,
        effector_type='rigid_arm26',
        max_ep_duration=1.0,
        batch_size=32,
        early_stopping='none',
        max_epochs=20000,
        proprioception_delay=50,
        vision_delay=100,
    )
    # test_config = dev_test_config
    test_config = full_run_test_config

    set_global_seed(test_config.seed)   # seed BEFORE building env + networks (weight init + target sampling)
    NullEnv, CurlEnv = resolve_training_envs(test_config)
    env = NullEnv(config=test_config)
    curl_env = (CurlEnv(config=test_config)
                if test_config.training_regime == 'interleaved' else None)
    
    task_net, pred_net = construct_architecture(test_config, env, device)
    
    print("--- Architecture Check ---")
    print(f"Task Network instantiated: {task_net is not None}")
    print(f"Task Network Input Dimension: {task_net.gru.input_size}")
    if pred_net:
        print(f"Predictive Network instantiated: {pred_net is not None}")
        print(f"Predictive Network Input Dimension: {pred_net.gru.input_size}")
        
    print("\n--- Starting Training ---")

    # To resume an interrupted run, set RESUME_FROM to its run directory (continues from training_state.pt).
    RESUME_FROM = None

    try:
        train_model(test_config, task_net, pred_net, env, device, curl_env, resume_from=RESUME_FROM)
    except KeyboardInterrupt:
        # The best model + logs + resume checkpoint from the last validation are already on disk in the
        # run directory printed at the start of training. Exit cleanly instead of a traceback.
        print("\n--- Training interrupted (Ctrl-C) --- best model, logs and resume checkpoint are in the run directory printed above.")

    end_perf_time = time.perf_counter()
    end_timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total_duration_seconds = end_perf_time - start_perf_time
    hours = int(total_duration_seconds // 3600)
    minutes = int((total_duration_seconds % 3600) // 60)
    seconds = int(total_duration_seconds % 60)
    
    print("\n--- Execution Completed ---")
    print(f"End Time: {end_timestamp}")
    print(f"Total Compute Duration: {hours:02d}:{minutes:02d}:{seconds:02d} ({total_duration_seconds:.2f} total seconds)")